import type { NextPage } from 'next'
import Head from 'next/head'

import { TcsAttribute } from '@truechoice-solutions/ui'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ padding: "10px" }}>
        <TcsAttribute
          attributes={[
            {
              "name": "color",
              "levels": [
                {
                  "name": "red",
                  "languageMap": {
                    "displayname": "Red",
                    "description": "The color red"
                  },
                  "modelValue": "9.20",
                  "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]color/[Level]red"
                },
                {
                  "name": "blue",
                  "languageMap": {
                    "displayname": "Blue",
                    "description": "The color blue"
                  },
                  "modelValue": 5,
                  "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]color/[Level]blue"
                }
              ],
              "languageMap": {
                "shortname.levels": "Color"
              },
              "profileMap": {
                "hidden": [
                  "false"
                ]
              },
              "modelValue": "50",
              "shortName": "color",
              "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]color"
            },
            {
              "name": "size",
              "levels": [
                {
                  "name": "small",
                  "languageMap": {
                    "displayname": "Small",
                    "description": "Size small"
                  },
                  "modelValue": "7.80",
                  "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]size/[Level]small"
                },
                {
                  "name": "medium",
                  "languageMap": {
                    "displayname": "Medium",
                    "description": "Size medium"
                  },
                  "modelValue": 5,
                  "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]size/[Level]medium"
                }
              ],
              "languageMap": {
                "shortname.levels": "Size"
              },
              "profileMap": {
                "hidden": [
                  "false"
                ]
              },
              "modelValue": "50",
              "shortName": "size",
              "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]size"
            },
            {
              "name": "Hidden Price",
              "levels": [
                {
                  "name": "0",
                  "modelValue": 10,
                  "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]Hidden Price/[Level]0"
                },
                {
                  "name": "1",
                  "modelValue": 0,
                  "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]Hidden Price/[Level]1"
                }
              ],
              "profileMap": {
                "hidden": [
                  "true"
                ]
              },
              "modelValue": "50",
              "shortName": "Hidden Price",
              "resolvableName": "[Client]tcsapp/[Game]tcsapp/[Attribute]Hidden Price"
            }
          ]}
          title="Moc TCS App"
          updateAttributeValue={(shortName, value) => undefined}
        />
      </main>

    </div>
  )
}

export default Home
